### ISSUE TITLE
how to fix

### ISSUE THREAD

**Issue by lwlbeng** [NRB-Tech/nRF5-cmake-scripts-example-base#1]
`Traceback (most recent call last):
  File "/Users/l/nrf52_Clion/toolchains/nRF5/nrf5SDKforMeshv400src/CMake/nrfjprog.py", line 102, in <module>
    main()
  File "/Users/l/nrf52_Clion/toolchains/nRF5/nrf5SDKforMeshv400src/CMake/nrfjprog.py", line 95, in main
    with multiprocessing.Pool(len(devices)) as p:
AttributeError: __exit__
make[3]: *** [src/CMakeFiles/flash_bl_merge_example] Error 1
make[2]: *** [src/CMakeFiles/flash_bl_merge_example.dir/all] Error 2
make[1]: *** [src/CMakeFiles/flash_bl_merge_example.dir/rule] Error 2
make: *** [flash_bl_merge_example] Error 2
`

**Comment by lwlbeng** [comment]
![image](https://user-images.githubusercontent.com/24000731/149872854-c791a085-d808-43a6-bc07-498ef86f55b7.png)
